# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "thunderbolt" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-ba88ccb5-5cf3-4633-a82c-13cdf705eb2b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ba88ccb5-5cf3-4633-a82c-13cdf705eb2b".device = "/dev/disk/by-uuid/ba88ccb5-5cf3-4633-a82c-13cdf705eb2b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/20B3-7C5A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-336e1b38-8974-4e00-bd8c-623ad4679c0e"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
