# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-6794ce8b-52b2-4d2c-bf1b-95a76138d527";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-6794ce8b-52b2-4d2c-bf1b-95a76138d527".device = "/dev/disk/by-uuid/6794ce8b-52b2-4d2c-bf1b-95a76138d527";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BA59-2897";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-16bc12d7-c54f-43a2-bf2c-8ceb18c87b3c";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
